version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb+srv://jeanalexistaddei:3AtAGveoDeHmxqNv@targetdummybdd.4jjdl.mongodb.net/MovieRandomizer?retryWrites=true&w=majority
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
