name: Pull Request to Dev

on:
  pull_request:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      MONGO_URI: MONGO_URI=mongodb+srv://jeanalexistaddei:3AtAGveoDeHmxqNv@targetdummybdd.4jjdl.mongodb.net/MovieRandomizer?retryWrites=true&w=majority
      MONGO_URI_TEST: mongodb://localhost:27017/movieDB
      PORT: 5000

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Backend Setup and Tests
    - name: Setup Node.js for Backend
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install dependencies for Backend
      run: |
        cd backend
        npm install

    - name: Seed the Database
      run: |
        cd backend
        node seed.js

    - name: Run Backend Integration Tests
      run: |
        cd backend
        npm run test:integration

    # Frontend Setup and Tests
    - name: Setup Node.js for Frontend
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install dependencies for Frontend
      run: |
        cd frontend
        npm install

    - name: Run Frontend Tests
      if: false
      run: |
        cd frontend
        npm test
