name: Push to Staging Branch

on:
  push:
    branches:
      - dev

jobs:
  push-to-staging:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"

    - name: Push to Staging
      run: |
        git fetch origin
        git checkout staging || git checkout -b staging
        git merge --no-ff dev -m "Auto-merge from dev to staging"
        git push origin staging
